### PR TITLE
Updated multiple aspects of the module

### PR DESCRIPTION
**Pull request by scottsteinbeck**
- Removed CFMLParser Dependency
- Made custom updates to brushes for SyntaxHighlighter
- Fixed code line lookup error
- updated styles to better match the original Whoops Module

### CODE REVIEW

**Comment by elpete** [comment]
Okay, finally got around to this.  This is awesome, thank you.  Just a couple of tweaks.

If a variable in the `rc` or `prc` is complex, it doesn't align with the rest of the variables.  Here's an example.

image

A similar thing happens in the `Application` scope.  It looks like the dumps are all at the top, not inline with their variable.

image

That's it.  If you can fix that minor styling issue, let's get this merged!

**Comment by elpete** [comment]
If you are feeling inspired, if we can get the information from these sections somewhere in whoops It doesn't have to be in the same place.  For instance, our `type` and `message` are shown in the top left.

I'm thinking we might be able to use the `RequestContext`'s `getMemento` to show everything we know about the event.  Then `url`, `form`, and `getHTTPContent`.

image

image

Thank you so much!

**Comment by elpete** [comment]
I didn't quite finish my last thought.  It was that with those last additions, I think we have a really good shot of having this be the default development error template in `coldbox@6`.

**Comment by elpete** [comment]
I'd still love those other changes, but I'd like to merge now so I can add a new feature off of this work.  Thanks again!

**Comment by scottsteinbeck** [comment]
Working on them now should be done shortly

**Pull request merged**
